import time
import traceback

from dtntools.dtncla.udp import UdpRxSocket, UdpTxSocket
from dtntools.dtngen.blocks import (
    BundleAgeBlock,
    CanonicalBlock,
    CompressedReportingBlock,
    CustodyTransferBlock,
    HopCountBlock,
    PayloadBlock,
    PayloadBlockSettings,
    PrevNodeBlock,
    PrimaryBlock,
    PrimaryBlockSettings,
    UnknownBlock,
)
from dtntools.dtngen.bundle import Bundle
from dtntools.dtngen.types import (
    EID,
    BlockPCFlags,
    BlockType,
    BundlePCFlags,
    CRCFlag,
    CRCType,
    CreationTimestamp,
    CREBData,
    CTEBData,
    HopCountData,
    StatusRRFlags,
    TypeWarning,
)


def create_test_bundle():
    """Create a test bundle."""
    # Define primary block settings for generation - everything is like in creating
    # a primary block, except creation_timestamp is a dictionary with settings
    # options
    primary_block_settings = PrimaryBlockSettings(
        version=7,
        control_flags=BundlePCFlags.MUST_NOT_FRAGMENT,
        crc_type=CRCType.CRC16_X25,
        dest_eid=EID({"uri": 2, "ssp": {"node_num": 200, "service_num": 1}}),
        src_eid=EID({"uri": 2, "ssp": {"node_num": 100, "service_num": 1}}),
        rpt_eid=EID({"uri": 2, "ssp": {"node_num": 100, "service_num": 1}}),
        creation_timestamp={
            "time": {"start": 755533838904, "increment": 256},
            "sequence": {"start": 0},
        },
        lifetime=3600000,
        crc=CRCFlag.CALCULATE,
    )

    # Payload block setting is like in creating a payload block, except for the
    # payload which is a dictionary with the size of payload to generate (in bytes)
    payload_block_settings = PayloadBlockSettings(
        blk_type=BlockType.AUTO,
        blk_num=1,
        control_flags=0,
        crc_type=CRCType.CRC16_X25,
        payload={"min_size": 10000, "max_size": 10000},
        crc=CRCFlag.CALCULATE,
    )

    # Bundles are then generated by the calling the Bundle @classmethod generate
    # with the count and the primary and canonical block settings from above. An
    # list is returned with the specified number of bundles
    generated_bundles = Bundle.generate(
        num_bundles=1,
        pri_settings=primary_block_settings,
        # The canon_settings is an array of settings instances. You could create
        # bundles with multiple canonical blocks by providing multiple settings
        # instances, though currently only the payload block is supported. You can
        # create bundles erroneously with multiple payload blocks or even no blocks
        canon_settings=[payload_block_settings],
    )

    # Encode the bundle
    encoded = generated_bundles[0].to_bytes()
    return encoded


RECEIVER_IP = "127.0.0.1"
RECEIVER_PORT = 13709

# Proc Start here
data_receiver = UdpRxSocket(RECEIVER_IP, RECEIVER_PORT)
# Create UDP data sender with a 1000 Mbps rate limit
data_sender = UdpTxSocket(RECEIVER_IP, RECEIVER_PORT, bps_limit=1000e6)

try:
    data_receiver.connect()
    data_sender.connect()

    test_bundle = create_test_bundle()

    # Send bundles to the DTN Node
    print("Sending packets to the DTN Node. Press ctrl-c to stop and retrieve packets.")
    while True:
        data_sender.write(test_bundle)

except KeyboardInterrupt:
    print("\nStopping the read and getting the read bundles")
    rx_bundles = data_receiver.read_all()

    print(f"Packets sent = {data_sender.get_packets_sent()}")
    print(f"Packets received = {data_receiver.get_packets_received()}")

    print(f"rx_bundles length = {len(rx_bundles)}")

    print(f"{Bundle.from_bytes(rx_bundles[len(rx_bundles)-1])}")
    print(f"bps = {data_sender.get_bps()}")
    pass

except Exception:
    print(traceback.format_exc())

finally:
    data_receiver.disconnect()
    data_sender.disconnect()
