#
# NASA Docket No. GSC-19,559-1, and identified as "Delay/Disruption Tolerant Networking 
# (DTN) Bundle Protocol (BP) v7 Core Flight System (cFS) Application Build 7.0
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this 
# file except in compliance with the License. You may obtain a copy of the License at 
#
# http://www.apache.org/licenses/LICENSE-2.0 
#
# Unless required by applicable law or agreed to in writing, software distributed under 
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF 
# ANY KIND, either express or implied. See the License for the specific language 
# governing permissions and limitations under the License. The copyright notice to be 
# included in the software is as follows: 
#
# Copyright 2025 United States Government as represented by the Administrator of the 
# National Aeronautics and Space Administration. All Rights Reserved.
#
#
from dtntools.dtncla.udp import UdpTxSocket
from dtntools.dtngen.blocks import (
    BundleAgeBlock,
    CanonicalBlock,
    CompressedReportingBlock,
    CustodyTransferBlock,
    HopCountBlock,
    PayloadBlock,
    PayloadBlockSettings,
    PrevNodeBlock,
    PrimaryBlock,
    PrimaryBlockSettings,
    UnknownBlock,
)
from dtntools.dtngen.bundle import Bundle
from dtntools.dtngen.types import (
    EID,
    BlockPCFlags,
    BlockType,
    BundlePCFlags,
    CRCFlag,
    CRCType,
    CreationTimestamp,
    CREBData,
    CTEBData,
    HopCountData,
    InvalidCBOR,
    StatusRRFlags,
    TypeWarning,
)

# Define primary block settings for generation - everything is like in creating
# a primary block, except creation_timestamp is a dictionary with settings
# options
primary_block_settings = PrimaryBlockSettings(
    version=7,
    control_flags=BundlePCFlags.MUST_NOT_FRAGMENT,
    crc_type=CRCType.CRC16_X25,
    dest_eid=EID({"uri": 2, "ssp": {"node_num": 200, "service_num": 1}}),
    src_eid=EID({"uri": 2, "ssp": {"node_num": 100, "service_num": 1}}),
    rpt_eid=EID({"uri": 2, "ssp": {"node_num": 100, "service_num": 1}}),
    creation_timestamp={
        "time": {"start": 755533838904, "increment": 256},
        "sequence": {"start": 0},
    },
    lifetime=3600000,
    crc=CRCFlag.CALCULATE,
)

# Payload block setting is like in creating a payload block, except for the
# payload which is a dictionary with the size of payload to generate (in bytes)
payload_block_settings = PayloadBlockSettings(
    blk_type=BlockType.AUTO,
    blk_num=1,
    control_flags=0,
    crc_type=CRCType.CRC16_X25,
    payload={"min_size": 5000, "max_size": 5000},
    crc=CRCFlag.CALCULATE,
)

# Bundles are then generated by the calling the Bundle @classmethod generate
# with the count and the primary and canonical block settings from above. An
# list is returned with the specified number of bundles
generated_bundles = Bundle.generate(
    num_bundles=1,
    pri_settings=primary_block_settings,
    # The canon_settings is an array of settings instances. You could create
    # bundles with multiple canonical blocks by providing multiple settings
    # instances, though currently only the payload block is supported. You can
    # create bundles erroneously with multiple payload blocks or even no blocks
    canon_settings=[payload_block_settings],
)

packet = generated_bundles[0].to_bytes()

RECEIVER_IP = "127.0.0.1"
RECEIVER_PORT = 13708

print("Creating TX socket with 600 Mbps rate limit and 0.5 second inter-message delay")
data_sender = UdpTxSocket(
    RECEIVER_IP, RECEIVER_PORT, bps_limit=200e6, inter_msg_delay=0.5
)
data_sender.connect()

print("Sending 10 packets...")
try:
    for x in range(10):
        p = data_sender.write(packet)

except KeyboardInterrupt:
    pass


print(f"Initial bps = {data_sender.get_bps()}")

total_sz = int(2000e6)  # in bytes - does not include udp packet overhead
pkt_sz = len(packet)
num_pkts = total_sz // pkt_sz

print(
    f"Removing inter-message delay and sending {num_pkts} packets. Press ctrl-c to stop early."
)
data_sender.remove_inter_msg_delay()

try:
    for x in range(num_pkts):
        p = data_sender.write(packet)

except KeyboardInterrupt:
    pass

finally:
    print(f"packets sent = {data_sender.get_packets_sent()}")
    print(f"bps = {data_sender.get_bps()}")
    data_sender.disconnect()
